In [ ]:
import pandas as pd
import sqlalchemy
import pandas as pd
from sqlalchemy import create_engine
from pathlib import Path

In [3]:
DB_USER = "postgres"
DB_PASSWORD = "postgres"
DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "customer_revenue_platform"

engine = create_engine(
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

print("Connected Successfully")

Connected Successfully

In [ ]:
# showing all the model metrics stored in the database with comparison of accuracy, precision, recall, f1 score and roc auc of all the models
query = """
SELECT *
FROM model_metrics
ORDER BY roc_auc DESC
"""

model_metrics = pd.read_sql(
    query,
    engine
)

model_metrics

,model_name,accuracy,precision,recall,f1_score,roc_auc,run_date
0,XGBoost,0.991988,0.953157,0.781302,0.858716,0.993212,2026-08-08 12:11:38.966830
1,Random Forest,0.991259,0.912046,0.796327,0.850267,0.989922,2026-08-08 12:10:58.273394
2,Logistic Regression,0.952549,0.388612,0.911519,0.544910,0.981138,2026-08-08 12:10:36.447159

In [5]:
# showing teh bestt model based on the highest roc auc score
best_model = model_metrics.iloc[0]

print("Best Model:")
print(best_model)

Best Model:
model_name                       XGBoost
accuracy                        0.991988
precision                       0.953157
recall                          0.781302
f1_score                        0.858716
roc_auc                         0.993212
run_date      2026-08-08 12:11:38.966830
Name: 0, dtype: object

In [6]:
# ranking the models based on their roc auc score in descending order
model_metrics["rank"] = (
    model_metrics["roc_auc"]
    .rank(
        ascending=False
    )
)

model_metrics.sort_values(
    "rank"
)

,model_name,accuracy,precision,recall,f1_score,roc_auc,run_date,rank
0,XGBoost,0.991988,0.953157,0.781302,0.858716,0.993212,2026-08-08 12:11:38.966830,1.0
1,Random Forest,0.991259,0.912046,0.796327,0.850267,0.989922,2026-08-08 12:10:58.273394,2.0
2,Logistic Regression,0.952549,0.388612,0.911519,0.544910,0.981138,2026-08-08 12:10:36.447159,3.0